
module.exports.routes = {
  'GET /register' : {view : 'register'},
  'GET /forgot_password' : {view :'forgot_password'},
  'GET /lecturer_add_sub2' : { view : 'file_manager_L_add_sub2'},
  'GET /privateinfo' : {view:'file_manager_L_mng_privateInfo'},
  'GET /lecturer_mng_sub' : {view:'file_manager_L_mng_sub'},
  'GET /students_sub_doc' : {view:'subject_doc_dload'},
  'GET /students_sub_hw' : {view:'subject_hw_dload'},
  'GET /students_sub_news' : {view:'subject_news_dload'},
  'GET /students_sub_score' : {view:'subject_score_dload'},
  'GET /home' : {view : 'home'},
  'GET /subject_doc_dload2' : {view : 'subject_doc_dload2'},
  'GET /subject_hw_dload2' : {view : 'subject_hw_dload2'},
  'GET /subject_news_dload2' : {view : 'subject_news_dload2'},
  'GET /subject_score_dload2' : {view : 'subject_score_dload2'},
  'GET /index' :{view : 'index'},
  'GET /profileLec' : {view : 'profile_lecturer'},
  'GET /lecturer_detail' : {view : 'lecturer_detail'},
  'GET /compose_mail' : {view :'mail_compose'},
  'GET /mailbox_view' : {view : 'mail_detail'},
  'GET /select_subject_term' : {view : 'select_subject_term'},
  'GET /student_subject' : {view : 'student_subject'},
  'GET /register_for_teacher_by_admin' : {view : 'register_for_teacher'},
  // api เรียกข้อมูลมาใส่ combobox
  //'GET /contacts_Lec' : 'PageController.showContact_Lec',
  //'Get /students_sub' : {view : 'homepage'},

  'GET /' : 'PageController.showHomepage',
  'GET /contacts_Lec' : 'PageController.showContact_Lec',
  'GET /students_sub' : 'PageController.showSubject',
  'GET /login' : 'PageController.showLogin',

  'GET /getdata_on_combobox' : 'getData_on_combobox_Controller.getdata_on_combobox',
  'GET /getdata_on_term_subject' : 'getData_on_combobox_Controller.getdata_on_term_subject',
  'GET /getdata_on_year_subject' : 'getData_on_combobox_Controller.getdata_on_year_subject',


  'GET /logout' : 'logoutController.logout',

  //api
  'POST /insert_user_data' : 'RegisterController.insert_user_data',
  'POST /search_data' : 'loginController.search_data',
  'POST /search_data_password' : 'forgotpasswordController.search_data_password',
  'POST /postupload' : 'uploadfileController.upload',
  'POST /get_files' : 'uploadfileController.get_files',
  'POST /search_data_teacher' : 'profilelecController.search_data_teacher',
  'POST /search_data_teacher_to_show_contacts' : 'profilelecController.search_data_teacher_to_show_contacts',
  'POST /remove_files' : 'uploadfileController.remove_files',
  'POST /get_files_homework' : 'getfilesController.get_files_homework',
  'POST /get_files_documents' : 'getfilesController.get_files_documents',
  'POST /get_lecturer_name_of_subject' : 'getfilesController.get_lecturer_name_of_subject',
  'POST /get_files_news' : 'getfilesController.get_files_news',
  'POST /get_files_score' : 'getfilesController.get_files_score',
  'POST /insert_news_data' : 'getfilesController.insert_news_data',
  'POST /insert_data_to_db_teacher' : 'lec_sub_addController.insert_data_to_db_teacher',
  'POST /getdata_on_subject_search' : 'getData_on_combobox_Controller.getdata_on_subject_search',
  'POST /get_data_on_elasticsearch' :'lec_sub_addController.get_data_on_elasticsearch',
  'POST /delete_subject_on_elasticsearch' : 'lec_sub_addController.delete_subject_on_elasticsearch',
  'POST /get_term_year' : 'uploadfileController.get_term_year',
  'POST /put_mailbox_to_elasticsearch' : 'mailboxController.put_mailbox_to_elasticsearch',
  'POST /search_mailbox_subject' : 'mailboxController.search_mailbox_subject',
  'POST /get_subject_all' : 'lec_sub_addController.get_subject_all',
  'POST /remove_news' : 'getfilesController.delete_files_news',
  'POST /register_for_teacher_by_admin' : 'register_for_teacher_by_adminController.register_for_teacher_by_admin',
  'POST /update_view_subject' : 'student_subjectController.update_view_subject',
  'POST /insert_data_follower' : 'student_subjectController.insert_data_follower',
  'POST /insert_type_for_log_follow' : 'lec_sub_addController.insert_type_for_log_follow',
  'POST /search_data_for_the_followers' : 'student_subjectController.search_data_for_the_followers',
  'POST /search_data_for_the_views' : 'student_subjectController.search_data_for_the_views',
  'POST /search_indi_data_in_student_subject' : 'student_subjectController.search_indi_data_in_student_subject',
  'POST /update_data_follower' : 'student_subjectController.update_data_follower'



};
